export const PriceRanges = {
  UNDER_ONE_THOUSANDS: 'UNDER_ONE_THOUSANDS',
  ONE_THOUSANDS: 'ONE_THOUSANDS',
  TWO_THOUSANDS: 'TWO_THOUSANDS',
  THREE_THOUSANDS: 'THREE_THOUSANDS',
  OVER_THREE_THOUSANDS: 'OVER_THREE_THOUSANDS',
} as const;

export const FoodTypes = {
  KOREAN: 'KOREAN',
  JAPANESE: 'JAPANESE',
  CHINESE: 'CHINESE',
  WESTERN: 'WESTERN',
  SNACK: 'SNACK',
  ASIAN: 'ASIAN',
} as const;
